# Generated by Django 5.2.8 on 2025-12-03 08:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('type', models.CharField(choices=[('income', 'Entrada'), ('expenseSaída', 'Expense')], verbose_name='Tipo')),
                ('date', models.DateField(verbose_name='Data')),
            ],
        ),
    ]
